# Generated by Django 4.2.16 on 2024-11-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_cps', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=0)),
                ('noise', models.BooleanField(default=False)),
                ('total_dose', models.FloatField(default=0.0)),
                ('dose_rate', models.FloatField(default=0.0)),
                ('alert', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detectors', to='demodos_ui.group')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detectors', to='demodos_ui.location')),
            ],
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='detector_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='demodos_ui.detector'),
        ),
        migrations.DeleteModel(
            name='DetectorUser',
        ),
    ]
