# Generated by Django 4.2.16 on 2024-11-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0002_detector_alter_historicaldata_detector_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='threshold',
            new_name='set_cps',
        ),
        migrations.AddField(
            model_name='detector',
            name='set_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
