# Generated by Django 4.2.16 on 2024-12-01 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0003_rename_threshold_detector_set_cps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('PAD', 'PAD'), ('DDU', 'DDU')], max_length=3)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('battery_status', models.IntegerField(default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('charging_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='detector',
            name='DDU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detector_ddu', to='demodos_ui.device'),
        ),
        migrations.AddField(
            model_name='detector',
            name='PAD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detector_pad', to='demodos_ui.device'),
        ),
    ]
