# Generated by Django 4.2.16 on 2024-12-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0004_device_detector_ddu_detector_pad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='battery_status',
            new_name='battery_level',
        ),
    ]
