# Generated by Django 4.2.16 on 2024-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0006_alter_device_charging_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fw_version',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
