# Generated by Django 4.2.16 on 2024-12-02 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0007_device_fw_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='DDU',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='PAD',
        ),
        migrations.AddField(
            model_name='device',
            name='detector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='demodos_ui.detector'),
        ),
    ]
