# Generated by Django 4.2.16 on 2024-12-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0008_remove_detector_ddu_remove_detector_pad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='detector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='demodos_ui.detector'),
        ),
    ]
