# Generated by Django 4.2.16 on 2024-12-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0009_alter_device_detector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='current_cps',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='set_cps',
        ),
        migrations.AddField(
            model_name='detector',
            name='data_source',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('GROUP', 'Group'), ('LOCATION', 'Location')], default='LOCAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('PAD', 'PAD'), ('DDU', 'DDU')], default='PAD', max_length=3),
        ),
    ]
