# Generated by Django 4.2.16 on 2024-12-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0010_remove_detector_current_cps_remove_detector_set_cps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='set_threshold',
            new_name='threshold',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='alert',
        ),
        migrations.AddField(
            model_name='detector',
            name='set_dose_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
