# Generated by Django 4.2.16 on 2024-12-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0012_detector_set_threshold_alter_detector_threshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='noise',
            new_name='set_noise',
        ),
    ]
