# Generated by Django 4.2.16 on 2024-12-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0013_rename_noise_detector_set_noise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='threshold',
        ),
    ]
