# Generated by Django 4.2.16 on 2024-12-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0014_remove_detector_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='cps',
            field=models.IntegerField(default=0),
        ),
    ]
