# Generated by Django 4.2.16 on 2024-12-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demodos_ui', '0015_detector_cps'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
