services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - 6000:8000
    depends_on:
      - postgres
      - redis
    environment:
      - ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    networks:
      - app_network

  task:
    build:
      context: .
    command: python run_task.py
    environment:
      - DJANGO_SETTINGS_MODULE=demodos_ui.settings
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7
    command: ["redis-server"]
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge